05.django/vscode/0317/03_ORM/articles/urls.py
from django.urls import path
from . import views


# app_name은 이 변수명으로 작성해야 정상 작동한다.
app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
]

05.django/vscode/0317/03_ORM/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    

05.django/vscode/0317/03_ORM/articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def index(request):
    # 모든 게시글 보여줘
    articles = Article.objects.all()
    # for article in articles:
    #     print(article.pk)
    #     print(article.title)
    #     print(article.content)
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # print(dir(request))
    print('='*30)
    print(request.GET)
    print('='*30)

    title = request.GET.get('title')
    content = request.GET.get('content')

    print(title, content)
    
    # ORM
    # class.manager.queryAPI
    # Article.objects.create()


    # 1. article instance 생성하는 방법 (더 많이 사용) 
    article = Article()
    article.title = title
    article.content = content
    print(article.title)
    print(article.content)
    # 아직 db에 반영된 것은 아님
    print(article.pk)
    # db에 위의 내용을 반영하는 방법은?
    article.save()
    print('db에 저장 후')
    print(article.pk)


    # 2. 두번째 방법 Class.Manager.Query API
    # Article.objects.create(title=title, content=content)

    return render(request, 'articles/create.html')

05.django/vscode/0317/03_ORM/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글이 생성 되었습니다.</h1>
  <a href="{% url 'articles:index' %}">[메인 페이지로...]</a>
{% endblock content %}

05.django/vscode/0317/03_ORM/articles/templates/articles/index.html
{% extends 'base.html' %} {% block content %}
<h1>INDEX PAGE</h1>
<a href="{% url 'articles:new' %}">[NEW]</a>
<hr />
{% for article in articles %}
<p>{{ article.pk }}</p>
<p>{{ article.title }}</p>
<p>{{ article.content }}</p>
<hr />
{% endfor %} {% endblock content %}

05.django/vscode/0317/03_ORM/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시글 생성 페이지</h1>

  <form action="{% url 'articles:create' %}">
    {% comment %} 제목 {% endcomment %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name='title'>

    {% comment %} 내용 {% endcomment %}
    <label for="content">내용 : </label>
    <input type="text" id="content" name="content">

    {% comment %} 제출 버튼 {% endcomment %}
    <input type="submit">
  </form>
{% endblock content %}